export const attributeTable = [
  {
    id: 0,
    name: "Background",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
      },
      {
        id: 1,
        mint: null,
        name: "Aether",
        stats: 1.3051,
      },
      {
        id: 2,
        mint: null,
        name: "Aqua",
        stats: 9.9572,
      },
      {
        id: 3,
        mint: null,
        name: "City",
        stats: 2.644,
      },
      {
        id: 4,
        mint: null,
        name: "Black",
        stats: 9.946,
      },
      {
        id: 5,
        mint: null,
        name: "Galaxy",
        stats: 0.3713,
      },
      {
        id: 6,
        mint: null,
        name: "Graveyard",
        stats: 2.9028,
      },
      {
        id: 7,
        mint: null,
        name: "Gray",
        stats: 10.4748,
      },
      {
        id: 8,
        mint: null,
        name: "Lime",
        stats: 3.2291,
      },
      {
        id: 9,
        mint: null,
        name: "Purple",
        stats: 10.6773,
      },
      {
        id: 10,
        mint: null,
        name: "Red",
        stats: 10.171,
      },
      {
        id: 11,
        mint: null,
        name: "White",
        stats: 10.1373,
      },
      {
        id: 12,
        mint: null,
        name: "Yellow",
        stats: 9.721,
      },
      {
        id: 13,
        mint: null,
        name: "Subway",
        stats: 7.3807,
      },
      {
        id: 14,
        mint: null,
        name: "Toxic",
        stats: 1.9352,
      },
      {
        id: 15,
        mint: null,
        name: "Underworld",
        stats: 0.6976,
      },
      {
        id: 16,
        mint: null,
        name: "Valleyside",
        stats: 8.4496,
      },
      {
        id: 65534,
        mint: null,
        name: "Dark",
      },
      {
        id: 65535,
        mint: null,
        name: "Blank",
      },
    ],
  },
  {
    id: 1,
    name: "Body",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
      },
      {
        id: 1,
        mint: null,
        name: "Aqua",
        stats: 19.0482,
      },
      {
        id: 2,
        mint: null,
        name: "Black",
        stats: 2.239,
      },
      {
        id: 3,
        mint: null,
        name: "Lime",
        stats: 20.8371,
      },
      {
        id: 4,
        mint: null,
        name: "Default",
        stats: 42.563,
      },
      {
        id: 5,
        mint: null,
        name: "Purple",
        stats: 4.2079,
      },
      {
        id: 6,
        mint: null,
        name: "Rainbow",
        stats: 0.7538,
      },
      {
        id: 7,
        mint: null,
        name: "Red",
        stats: 4.2304,
      },
      {
        id: 8,
        mint: null,
        name: "Solana",
        stats: 0.7088,
      },
      {
        id: 9,
        mint: null,
        name: "White",
        stats: 1.6202,
      },
      {
        id: 10,
        mint: null,
        name: "Yellow",
        stats: 3.7916,
      },
    ],
  },
  {
    id: 2,
    name: "Companion",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
        stats: 99.1337,
      },
      {
        id: 1,
        mint: null,
        name: "Angel",
        stats: 0.18,
      },
      {
        id: 2,
        mint: null,
        name: "Demon",
        stats: 0.315,
      },
      {
        id: 3,
        mint: null,
        name: "Electricity",
        stats: 0.1575,
      },
      {
        id: 4,
        mint: null,
        name: "Fire",
        stats: 0.1913,
      },
      {
        id: 5,
        mint: null,
        name: "Solana",
        stats: 0.0225,
      },
    ],
  },
  {
    id: 3,
    name: "Expressions",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
      },
      {
        id: 1,
        mint: null,
        name: "Big Smile (Droopy)",
      },
      {
        id: 2,
        mint: null,
        name: "Big Smile (Evil)",
      },
      {
        id: 3,
        mint: null,
        name: "Big Smile (Happy)",
      },
      {
        id: 4,
        mint: null,
        name: "Big Smile (Stare)",
      },
      {
        id: 5,
        mint: null,
        name: "Big Smile (Sunglasses)",
      },
      {
        id: 6,
        mint: null,
        name: "Doink (Droopy)",
      },
      {
        id: 7,
        mint: null,
        name: "Doink (Evil)",
      },
      {
        id: 8,
        mint: null,
        name: "Doink (Sunglasses)",
      },
      {
        id: 9,
        mint: null,
        name: "Frown (Evil)",
      },
      {
        id: 10,
        mint: null,
        name: "Gasp (Evil)",
      },
      {
        id: 11,
        mint: null,
        name: "Gasp (Stare)",
      },
      {
        id: 12,
        mint: null,
        name: "Happy (Evil)",
      },
      {
        id: 13,
        mint: null,
        name: "Happy (Happy)",
      },
      {
        id: 14,
        mint: null,
        name: "Happy (Kawaii)",
      },
      {
        id: 15,
        mint: null,
        name: "Happy (VR)",
      },
      {
        id: 16,
        mint: null,
        name: "Mustache (Droopy)",
      },
      {
        id: 17,
        mint: null,
        name: "Mustache (Happy)",
      },
      {
        id: 18,
        mint: null,
        name: "Mustache (Stare)",
      },
      {
        id: 19,
        mint: null,
        name: "Mustache (Sunglasses)",
      },
      {
        id: 20,
        mint: null,
        name: "No Mouth (Droopy)",
      },
      {
        id: 21,
        mint: null,
        name: "No Mouth (Evil)",
      },
      {
        id: 22,
        mint: null,
        name: "No Mouth (Happy)",
      },
      {
        id: 23,
        mint: null,
        name: "No Mouth (Kawaii)",
      },
      {
        id: 24,
        mint: null,
        name: "No Mouth (Snake)",
      },
      {
        id: 25,
        mint: null,
        name: "No Mouth (Stare)",
      },
      {
        id: 26,
        mint: null,
        name: "No Mouth (Sunglasses)",
      },
      {
        id: 27,
        mint: null,
        name: "No Mouth (VR)",
      },
      {
        id: 28,
        mint: null,
        name: "Small Smile (Evil)",
      },
      {
        id: 29,
        mint: null,
        name: "Small Smile (Happy)",
      },
      {
        id: 30,
        mint: null,
        name: "Medium Smile (Evil)",
      },
      {
        id: 31,
        mint: null,
        name: "Medium Smile (Happy)",
      },
      {
        id: 32,
        mint: null,
        name: "Medium Smile (Sunglasses)",
      },
      {
        id: 33,
        mint: null,
        name: "Smirk (Droopy)",
      },
      {
        id: 34,
        mint: null,
        name: "Smirk (Evil)",
      },
      {
        id: 35,
        mint: null,
        name: "Smirk (Sunglasses)",
      },
      {
        id: 36,
        mint: null,
        name: "Snake (Snake)",
      },
    ],
  },
  {
    id: 4,
    name: "Hand",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
      },
      {
        id: 1,
        mint: null,
        name: "Balloon (Aqua)",
      },
      {
        id: 2,
        mint: null,
        name: "Balloon (Lime)",
      },
      {
        id: 3,
        mint: null,
        name: "Balloon (Red)",
      },
      {
        id: 4,
        mint: null,
        name: "Balloon (Solana)",
      },
      {
        id: 5,
        mint: null,
        name: "Demon Trident",
      },
      {
        id: 6,
        mint: null,
        name: "Diamond Sword",
      },
      {
        id: 7,
        mint: null,
        name: "Katana (Dual Wield)",
      },
      {
        id: 8,
        mint: null,
        name: "Katana",
      },
      {
        id: 9,
        mint: null,
        name: "Lightsword (Blue)",
      },
      {
        id: 10,
        mint: null,
        name: "Lightsword (Red)",
      },
      {
        id: 11,
        mint: null,
        name: "Magic Wand",
      },
      {
        id: 12,
        mint: null,
        name: "Nunchuck",
      },
      {
        id: 13,
        mint: null,
        name: "Pizza",
      },
      {
        id: 14,
        mint: null,
        name: "Flowers",
      },
      {
        id: 15,
        mint: null,
        name: "Reaper Scythe",
      },
      {
        id: 16,
        mint: null,
        name: "Scimitar (Red)",
      },
      {
        id: 17,
        mint: null,
        name: "Spell (Dark)",
      },
      {
        id: 18,
        mint: null,
        name: "Spell (Fireball)",
      },
      {
        id: 19,
        mint: null,
        name: "Spell (Sol Fireball)",
      },
      {
        id: 20,
        mint: null,
        name: "Staff (Electric)",
      },
      {
        id: 21,
        mint: null,
        name: "Staff (Golden)",
      },
      {
        id: 69,
        mint: null,
        name: "Penetrator",
      },
    ],
  },
  {
    id: 5,
    name: "Head",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
        stats: 42.473,
      },
      {
        id: 1,
        mint: null,
        name: "Element (Dark)",
        stats: 0.8326,
      },
      {
        id: 2,
        mint: null,
        name: "Element (Diamond)",
        stats: 0.4275,
      },
      {
        id: 3,
        mint: null,
        name: "Element (Electric)",
        stats: 0.225,
      },
      {
        id: 4,
        mint: null,
        name: "Element (Fairy)",
        stats: 0.5738,
      },
      {
        id: 5,
        mint: null,
        name: "Element (Fire)",
        stats: 0.0675,
      },
      {
        id: 6,
        mint: null,
        name: "Element (Ghost)",
        stats: 0.2588,
      },
      {
        id: 7,
        mint: null,
        name: "Element (Grass)",
        stats: 1.2151,
      },
      {
        id: 8,
        mint: null,
        name: "Element (Radioactive)",
        stats: 0.1013,
      },
      {
        id: 9,
        mint: null,
        name: "Element (Solana Fire)",
        stats: 0.09,
      },
      {
        id: 10,
        mint: null,
        name: "Element (Water)",
        stats: 0.9676,
      },
      {
        id: 11,
        mint: null,
        name: "Element (Zombie)",
        stats: 0.315,
      },
      {
        id: 12,
        mint: null,
        name: "Halo (Black)",
        stats: 1.0801,
      },
      {
        id: 13,
        mint: null,
        name: "Halo (Solana)",
        stats: 0.9001,
      },
      {
        id: 14,
        mint: null,
        name: "Flower Crown",
        stats: 3.0828,
      },
      {
        id: 15,
        mint: null,
        name: "Halo (White)",
        stats: 1.1814,
      },
      {
        id: 16,
        mint: null,
        name: "Halo",
        stats: 1.6202,
      },
      {
        id: 17,
        mint: null,
        name: "Headband (Black)",
        stats: 4.1067,
      },
      {
        id: 18,
        mint: null,
        name: "Headband (Lime)",
        stats: 4.4442,
      },
      {
        id: 19,
        mint: null,
        name: "Headband (Pink)",
        stats: 4.0729,
      },
      {
        id: 20,
        mint: null,
        name: "Headband (Red)",
        stats: 3.7691,
      },
      {
        id: 21,
        mint: null,
        name: "Horns (Black)",
        stats: 1.3051,
      },
      {
        id: 22,
        mint: null,
        name: "Horns (Red)",
        stats: 2.464,
      },
      {
        id: 23,
        mint: null,
        name: "Horns (White)",
        stats: 1.2151,
      },
      {
        id: 24,
        mint: null,
        name: "Miner Helmet",
        stats: 1.6202,
      },
      {
        id: 25,
        mint: null,
        name: "Party Hat (Blue)",
        stats: 3.1728,
      },
      {
        id: 26,
        mint: null,
        name: "Party Hat (Lime)",
        stats: 2.1377,
      },
      {
        id: 27,
        mint: null,
        name: "Party Hat (Purple)",
        stats: 2.2952,
      },
      {
        id: 28,
        mint: null,
        name: "Party Hat (Red)",
        stats: 2.8578,
      },
      {
        id: 29,
        mint: null,
        name: "Party Hat (Yellow)",
        stats: 2.2952,
      },
      {
        id: 30,
        mint: null,
        name: "Tophat",
        stats: 5.0293,
      },
      {
        id: 31,
        mint: null,
        name: "Wizard Hat",
        stats: 3.8029,
      },
    ],
  },
  {
    id: 6,
    name: "Outfit",
    items: [
      {
        id: 0,
        mint: null,
        name: "None",
        stats: 23.4811,
      },
      {
        id: 1,
        mint: null,
        name: "Angel Wings",
        stats: 0.5738,
      },
      {
        id: 2,
        mint: null,
        name: "Black Hoodie (Solana)",
        stats: 5.5243,
      },
      {
        id: 3,
        mint: null,
        name: "Black Hoodie",
        stats: 17.3267,
      },
      {
        id: 4,
        mint: null,
        name: "Cowboy",
        stats: 14.5365,
      },
      {
        id: 5,
        mint: null,
        name: "Demon Wings",
        stats: 0.4838,
      },
      {
        id: 6,
        mint: null,
        name: "Elf",
        stats: 2.3402,
      },
      {
        id: 7,
        mint: null,
        name: "Jedi",
        stats: 2.5203,
      },
      {
        id: 8,
        mint: null,
        name: "Katana",
        stats: 2.8353,
      },
      {
        id: 9,
        mint: null,
        name: "Penguin",
        stats: 4.748,
      },
      {
        id: 10,
        mint: null,
        name: "Samurai",
        stats: 1.0126,
      },
      {
        id: 11,
        mint: null,
        name: "Sith",
        stats: 2.4527,
      },
      {
        id: 12,
        mint: null,
        name: "White Hoodie (Solana)",
        stats: 3.9041,
      },
      {
        id: 13,
        mint: null,
        name: "White Hoodie",
        stats: 16.9779,
      },
      {
        id: 14,
        mint: null,
        name: "Wizard Robe",
        stats: 1.2826,
      },
    ],
  },
];
